name: Github Action Demo
on: 
  workflow_dispatch:
    inputs: 
      server: 
        description: 'Environnement à utiliser'
        required: true
        default: 'dev'
jobs: 
  deploy-env:
    runs-on: ubuntu-latest
    steps:
      - name: Start Work
        run: echo "Workflow démarré sur ${{ github.ref }}"
      - name: Checkout
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/checkout@v4.1.1
      - name: Prod deploy
        if: ${{ github.event.inputs.server == 'prod' }}
        run: echo "PROD"
