name: Github Action Demo
on: 
  workflow_dispatch:
    inputs: 
      server: 
        description: 'Environnement à utiliser'
        required: true
        default: 'dev'
jobs: 
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Start Work
        run: echo "Workflow démarré"
      - name: Checkout
        uses: actions/checkout@v4.1.1
          
